version: 2
updates:
- package-ecosystem: "github-actions"
  directories:
    - "/"
    - "/.github/actions/sign-image"
  schedule:
      interval: "weekly"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
