FROM amd64/golang:1.17-buster

RUN apt-get update
RUN apt-get install -y build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev liblz4-dev libzstd-dev

ENV ROCKSDB_VERSION v6.22.1

# build RocksDB
RUN cd /tmp && \
    git clone https://github.com/facebook/rocksdb.git /tmp/rocksdb --depth 1 --single-branch --branch $ROCKSDB_VERSION && \
    cd rocksdb && \
    make static_lib && \
    make install-static

