[postgres2]
enabled = true
port = 5432
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "postgres"
username = "seaweedfs"
database = "seaweedfs"          # create or use an existing database
password = "seaweedfs"
schema = ""
sslmode = "disable"
connection_max_idle = 5
connection_max_open = 10
connection_max_lifetime_seconds = 0
