apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "seaweedfs.name" . }}-filer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: filer
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "swfs-filer"
    port: {{ .Values.filer.port }}
    targetPort: {{ .Values.filer.port }}
    protocol: TCP
  - name: "swfs-filer-grpc"
    port: {{ .Values.filer.grpcPort }}
    targetPort: {{ .Values.filer.grpcPort }}
    protocol: TCP
  {{- if .Values.filer.s3.enabled }}
  - name: "swfs-s3"
    port: {{ .Values.filer.s3.port }}
    targetPort: {{ .Values.filer.s3.port }}
    protocol: TCP
  {{- end }}
  {{- if .Values.filer.metricsPort }}
  - name: "metrics"
    port: {{ .Values.filer.metricsPort }}
    targetPort: {{ .Values.filer.metricsPort }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: filer
