{{- if .Values.volume.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-volume
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: volume
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.volume.annotations }}
  annotations:
    {{- toYaml .Values.volume.annotations | nindent 4 }}
{{- end }}
spec:
  clusterIP: None
  internalTrafficPolicy: {{ .Values.volume.internalTrafficPolicy | default "Cluster" }}
  ports:
  - name: "swfs-volume"
    port: {{ .Values.volume.port }}
    targetPort: {{ .Values.volume.port }}
    protocol: TCP
  - name: "swfs-volume-18080"
    port: {{ .Values.volume.grpcPort }}
    targetPort: {{ .Values.volume.grpcPort }}
    protocol: TCP
{{- if .Values.volume.metricsPort }}
  - name: "metrics"
    port: {{ .Values.volume.metricsPort }}
    targetPort: {{ .Values.volume.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: volume
{{- end }}
