// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mount.proto

package mount_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigureRequest struct {
	CollectionCapacity   int64    `protobuf:"varint,1,opt,name=collection_capacity,json=collectionCapacity,proto3" json:"collection_capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureRequest) Reset()         { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()    {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb691b440722b164, []int{0}
}

func (m *ConfigureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureRequest.Unmarshal(m, b)
}
func (m *ConfigureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureRequest.Marshal(b, m, deterministic)
}
func (m *ConfigureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureRequest.Merge(m, src)
}
func (m *ConfigureRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureRequest.Size(m)
}
func (m *ConfigureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureRequest proto.InternalMessageInfo

func (m *ConfigureRequest) GetCollectionCapacity() int64 {
	if m != nil {
		return m.CollectionCapacity
	}
	return 0
}

type ConfigureResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureResponse) Reset()         { *m = ConfigureResponse{} }
func (m *ConfigureResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureResponse) ProtoMessage()    {}
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb691b440722b164, []int{1}
}

func (m *ConfigureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureResponse.Unmarshal(m, b)
}
func (m *ConfigureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureResponse.Merge(m, src)
}
func (m *ConfigureResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureResponse.Size(m)
}
func (m *ConfigureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ConfigureRequest)(nil), "messaging_pb.ConfigureRequest")
	proto.RegisterType((*ConfigureResponse)(nil), "messaging_pb.ConfigureResponse")
}

func init() {
	proto.RegisterFile("mount.proto", fileDescriptor_fb691b440722b164)
}

var fileDescriptor_fb691b440722b164 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbf, 0x4b, 0xc7, 0x30,
	0x14, 0xc4, 0x2d, 0x82, 0xe0, 0xb3, 0x43, 0x4d, 0x17, 0x71, 0x50, 0xe9, 0xe4, 0x94, 0x80, 0xfe,
	0x07, 0xed, 0xec, 0x0f, 0xea, 0xe6, 0x60, 0x49, 0xe2, 0x6b, 0x0c, 0xb4, 0x79, 0xb1, 0x49, 0x10,
	0xff, 0x7b, 0x69, 0x2b, 0xb5, 0x08, 0xdf, 0x29, 0x81, 0x3b, 0x3e, 0x77, 0xef, 0xe0, 0x6c, 0xa4,
	0xe4, 0x22, 0xf7, 0x13, 0x45, 0x62, 0xf9, 0x88, 0x21, 0x48, 0x63, 0x9d, 0xe9, 0xbc, 0xaa, 0x1a,
	0x28, 0x1a, 0x72, 0xbd, 0x35, 0x69, 0xc2, 0x16, 0x3f, 0x13, 0x86, 0xc8, 0x04, 0x94, 0x9a, 0x86,
	0x01, 0x75, 0xb4, 0xe4, 0x3a, 0x2d, 0xbd, 0xd4, 0x36, 0x7e, 0x5f, 0x64, 0x37, 0xd9, 0xed, 0x71,
	0xcb, 0xfe, 0xa4, 0xe6, 0x57, 0xa9, 0x4a, 0x38, 0xdf, 0x41, 0x82, 0x27, 0x17, 0xf0, 0xee, 0x0d,
	0xf2, 0x17, 0x94, 0x5f, 0x88, 0xef, 0x0f, 0x73, 0x3a, 0x7b, 0x84, 0xd3, 0xcd, 0xc4, 0xae, 0xf8,
	0xbe, 0x05, 0xff, 0x5f, 0xe1, 0xf2, 0xfa, 0xa0, 0xbe, 0xd2, 0xab, 0xa3, 0xfa, 0x09, 0x8a, 0xb0,
	0xf2, 0xfb, 0xc0, 0xf5, 0x60, 0xd1, 0xc5, 0x1a, 0x96, 0xa8, 0xe7, 0xf9, 0xce, 0x57, 0x61, 0x6c,
	0xfc, 0x48, 0x8a, 0x6b, 0x1a, 0xc5, 0x66, 0xdc, 0xfd, 0xe6, 0x47, 0x78, 0x25, 0x96, 0x6d, 0x3a,
	0xaf, 0xd4, 0xc9, 0xb2, 0xcf, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x7b, 0x52, 0x4c,
	0x2e, 0x01, 0x00, 0x00,
}
