version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.2
    command: [
      "start-dev",
      "--import-realm",
      "--http-port=8180",
      "--hostname=http://keycloak:8180",
      "--hostname-strict=false"
    ]
    ports:
      - "8180:8180"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/seaweedfs-realm.json:/opt/keycloak/data/import/seaweedfs-realm.json:ro

  s3:
    image: chrislusf/seaweedfs:local
    command:
      -v=9
      server
      -ip=s3
      -filer
      -master.volumeSizeLimitMB=16
      -volume
      -volume.max=0
      -volume.preStopSeconds=1
      -s3
      -s3.config=/etc/seaweedfs/s3.json
      -s3.port=8000
      -s3.allowDeleteBucketNotEmpty=false
      -s3.iam.config=/etc/seaweedfs/iam.json
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
      - ./keycloak/iam.json:/etc/seaweedfs/iam.json
    environment:
      WEED_MASTER_VOLUME_GROWTH_COPY_OTHER: 1
    ports:
      - "8000:8000"
    depends_on:
      - keycloak
