# S3 API Server Configuration
# Used with "weed s3" or "weed server -s3"
# Put this file to one of the location, with descending priority
#    ./s3.toml
#    $HOME/.seaweedfs/s3.toml
#    /etc/seaweedfs/s3.toml

# NOTE: For IAM/credentials configuration, use a separate JSON file
# Example: weed s3 -config=s3_iam.json
# See: https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API

####################################################
# Key Management Service (KMS) for Server-Side Encryption
####################################################
# KMS providers for SSE-KMS and SSE-S3 encryption
# Configure different providers for different regions/environments

[kms]
default_provider = "aws-us-east-1"

# AWS KMS Provider
[kms.providers.aws-us-east-1]
type = "aws"
region = "us-east-1"
# Use IAM roles in production, access keys only for development
# access_key = "your-access-key"
# secret_key = "your-secret-key"

[kms.providers.aws-eu-west-1]
type = "aws"
region = "eu-west-1"

# Azure Key Vault Provider
[kms.providers.azure-keyvault]
type = "azure"
vault_url = "https://company.vault.azure.net/"
# Option 1: Service principal
tenant_id = "12345678-1234-1234-1234-123456789012"
client_id = "your-client-id"
client_secret = "your-client-secret"
# Option 2: Use managed identity (recommended in Azure)
# use_default_creds = true

# Google Cloud KMS Provider
[kms.providers.gcp-global]
type = "gcp"
project_id = "your-gcp-project"
location = "global"
key_ring = "seaweedfs-keyring"
# Option 1: Service account JSON file
credentials_file = "/path/to/service-account.json"
# Option 2: Use default credentials (recommended in GCP)
# use_default_credentials = true

# Local KMS Provider (development/testing only)
[kms.providers.local-dev]
type = "local"
# WARNING: Only for development/testing - NOT for production
enableOnDemandCreate = true

# Per-bucket KMS provider assignments
[kms.buckets.secure-data]
provider = "aws-us-east-1"

[kms.buckets.customer-files]
provider = "azure-keyvault"

[kms.buckets.test-bucket]
provider = "local-dev"
