name: "Kafka Quick Test (Load Test with Schema Registry)"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # Allow manual trigger

concurrency:
  group: ${{ github.head_ref }}/kafka-quicktest
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  kafka-client-quicktest:
    name: Kafka Client Load Test (Quick)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.24
        cache: true
        cache-dependency-path: |
          **/go.sum
      id: go

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: |
        # Ensure make is available
        sudo apt-get update -qq
        sudo apt-get install -y make

    - name: Validate test setup
      working-directory: test/kafka/kafka-client-loadtest
      run: |
        make validate-setup

    - name: Run quick-test
      working-directory: test/kafka/kafka-client-loadtest
      run: |
        # Run the quick-test target which includes:
        # 1. Building the gateway
        # 2. Starting all services (SeaweedFS, MQ broker, Schema Registry)
        # 3. Registering Avro schemas
        # 4. Running a 1-minute load test with Avro messages
        # Override GOARCH to build for AMD64 (GitHub Actions runners are x86_64)
        GOARCH=amd64 make quick-test
      env:
        # Docker Compose settings
        COMPOSE_HTTP_TIMEOUT: 300
        DOCKER_CLIENT_TIMEOUT: 300
        # Test parameters (set by quick-test, but can override)
        TEST_DURATION: 60s
        PRODUCER_COUNT: 1
        CONSUMER_COUNT: 1
        MESSAGE_RATE: 10
        VALUE_TYPE: avro

    - name: Show test results
      if: always()
      working-directory: test/kafka/kafka-client-loadtest
      run: |
        echo "========================================="
        echo "Test Results"
        echo "========================================="
        make show-results || echo "Could not retrieve results"

    - name: Show service logs on failure
      if: failure()
      working-directory: test/kafka/kafka-client-loadtest
      run: |
        echo "========================================="
        echo "Service Logs"
        echo "========================================="
        docker compose logs --tail=100 seaweedfs-master || echo "No master logs"
        echo "========================================="
        docker compose logs --tail=100 seaweedfs-mq-broker || echo "No broker logs"
        echo "========================================="
        docker compose logs --tail=100 kafka-gateway || echo "No gateway logs"
        echo "========================================="
        docker compose logs --tail=100 schema-registry || echo "No schema registry logs"
        echo "========================================="
        docker compose logs --tail=100 kafka-client-loadtest || echo "No loadtest logs"

    - name: Cleanup
      if: always()
      working-directory: test/kafka/kafka-client-loadtest
      run: |
        make clean || true
